# Generated by Django 5.1.2 on 2024-11-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.ImageField(blank=True, default='noImage.png', null=True, upload_to=''),
        ),
    ]
